_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.19.6
            "6": 4.35.2
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
DATASET:
    value:
        CACHED_DATASET_FOLDER: pre_existing_datasets/parallel_new_backbone_10epoch_init_012
        CACHED_DATASET_ROOT: pre_existing_datasets
        DATA_FILE: ../datasets/source_files/metadata_cleaned_permissive.tsv
        FLAT_CLASS: true
        GENETIC:
            FIX_PROTOTYPES: true
            MAX_NUM_PROTOTYPES_PER_CLASS: 8
            NUM_PROTOTYPES_PER_CLASS: 40
            PPNET_PATH: ../output/genetic_only/genetic_species_warm_001/images/10_push_weights.pth
            PROTOTYPE_SHAPE:
                - 64
                - 1
                - 1
        GENETIC_AUGMENTATION:
            DELETION_COUNT: 4
            INSERTION_COUNT: 4
            SUBSTITUTION_RATE: 0.05
        IMAGE:
            NUM_PROTOTYPE: 8
            NUM_PROTOTYPES_PER_CLASS: 10
            PPNET_PATH: ../output/image_only/image_species_120_80train_warm_001/images/10_push_weights.pth
            PROTOTYPE_SHAPE:
                - 2048
                - 1
                - 1
            SIZE: 256
            TRAIN_BATCH_SIZE: 80
            TRANSFORM_MEAN:
                - 0.485
                - 0.456
                - 0.406
            TRANSFORM_STD:
                - 0.229
                - 0.224
                - 0.225
        IMAGE_PATH: ../datasets/full_bioscan_images/
        MODE: 3
        PARALLEL_MODE: true
        PREEXISTING: false
        TEST_BATCH_SIZE: 100
        TRAIN_BATCH_SIZE: 80
        TRAIN_NOT_CLASSIFIED_PROPORTIONS:
            - 0
            - 0
            - 0
            - 0
        TRAIN_PUSH_BATCH_SIZE: 75
        TRAIN_VAL_TEST_SPLIT:
            - 80
            - 20
            - 20
        TREE_SPECIFICATION_FILE: class_trees/all_species_120.json
MODEL:
    value:
        DEVICE: cuda
        GENETIC_BACKBONE_PATH: backbones/genetic_species_001/genetic_species_001_best.pth
        GENETIC_MODE: false
        IMAGE_BACKBONE: resnetbioscan
        MULTI:
            MULTI_PPNET_PATH: NA
        PRUNE: false
        PRUNING_K: 6
        PRUNING_TAU: 3
        PRUNING_TYPE: quality
OPTIM:
    value:
        CEDA: false
        COEFS:
            CLST: 0.001
            CORRESPONDENCE: 1
            CRS_ENT: 20
            L1: 0.005
            SEP: -0.1
        CORRESPONDENCE_TYPE: Batched
        GLOBAL_CROSSENTROPY: false
        JOINT: false
        JOINT_OPTIMIZER_LAYERS:
            ADD_ON_LAYERS: 0.003
            FEATURES: 0.0001
            LR_STEP_SIZE: 5
            PROTOTYPE_VECTORS: 0.003
            WEIGHT_DECAY: 0.001
        LAST_LAYER_OPTIMIZER_LAYERS:
            LR: 0.0001
        NUM_JOINT_EPOCHS: 5
        NUM_PROTO_EPOCHS: 5
        NUM_TRAIN_EPOCHS: 100
        NUM_WARM_EPOCHS: 0
        PRUNE_START: 10
        PUSH_EPOCHS:
            - 5
            - 10
            - 15
            - 20
        PUSH_START: 50
        WARM_OPTIMIZER_LAYERS:
            ADD_ON_LAYERS: 0.003
            PROTOTYPE_VECTORS: 0.003
            WEIGHT_DECAY: 0.001
OUTPUT:
    value:
        IMG_DIR: ../output/images
        MODEL_DIR: ../output
        NO_SAVE: true
        PREPROCESS_INPUT_FUNCTION: null
        PROTO_BOUND_BOXES_FILENAME_PREFIX: bb
        PROTOTYPE_IMG_FILENAME_PREFIX: prototype-img
        PROTOTYPE_SELF_ACT_FILENAME_PREFIX: prototype-self-act
        WEIGHT_MATRIX_FILENAME: outputL_weights
RUN_NAME:
    value: parallel_new_backbone_10epoch_init_nopush_1000_003
SEED:
    value: 2024
