from yacs.config import CfgNode 
C = CfgNode()

C.RUN_NAME = "" 
C.SEED = 2024
C.MODE = 0
C.WANDB_MODE = "disabled"
C.DEVICE = ""

# Model
C.MODEL = CfgNode() 
C.MODEL.IMAGE = CfgNode()
C.MODEL.IMAGE.PPNET_PATH = ""
C.MODEL.IMAGE.BACKBONE_PATH = ""
C.MODEL.IMAGE.NUM_PROTOTYPES_PER_CLASS = 0
C.MODEL.IMAGE.PROTOTYPE_SHAPE = (0, 0, 0) 

C.MODEL.GENETIC = CfgNode()
C.MODEL.GENETIC.PPNET_PATH = ""
C.MODEL.GENETIC.BACKBONE_PATH = ""
C.MODEL.GENETIC.NUM_PROTOTYPES_PER_CLASS = 0
C.MODEL.GENETIC.PROTOTYPE_SHAPE = (0, 0, 0) 

# Dataset
C.DATASET = CfgNode()
C.DATASET.IMAGE_PATH = ""
C.DATASET.DATA_FILE = ""
C.DATASET.HIERARCHY_FILE = "" 

C.DATASET.CACHED_DATASET_FOLDER = ""

C.DATASET.TRAIN_NOT_CLASSIFIED_PROPORTIONS = [0, 0, 0, 0] 
C.DATASET.TRAIN_VAL_TEST_SPLIT = [0, 0, 0]

C.DATASET.TRANSFORMS = CfgNode()
C.DATASET.TRANSFORMS.GENETIC = CfgNode()
C.DATASET.TRANSFORMS.GENETIC.SUBSTITUTION_RATE = 0.0
C.DATASET.TRANSFORMS.GENETIC.DELETION_COUNT = 0
C.DATASET.TRANSFORMS.GENETIC.INSERTION_COUNT = 0

C.DATASET.TRANSFORMS.IMAGE = CfgNode()
C.DATASET.TRANSFORMS.IMAGE.SIZE = 256
C.DATASET.TRANSFORMS.IMAGE.MEAN = (0., 0., 0.)
C.DATASET.TRANSFORMS.IMAGE.STD = (0., 0., 0.)

C.DATASET.TRAIN_BATCH_SIZE = 0
C.DATASET.TEST_BATCH_SIZE = 0
C.DATASET.PUSH_BATCH_SIZE = 0


# OPTIMIZER
C.OPTIM = CfgNode() 

C.OPTIM.TRAIN = CfgNode() 
C.OPTIM.NUM_WARM_EPOCHS = 0
C.OPTIM.NUM_EPOCHS = 0
C.OPTIM.TRAIN.CORRESPONDENCE_TYPE = ""

C.OPTIM.TRAIN.COEFS = CfgNode()
C.OPTIM.TRAIN.COEFS.CORRESPONDENCE = 0.
C.OPTIM.TRAIN.CORRESPONDENCE_TYPE = "Batched" # One of ("Batched", "Single"). 

C.OPTIM.TRAIN.COEFS.GENETIC = CfgNode()
C.OPTIM.TRAIN.COEFS.GENETIC.CRS_ENT = 0.
C.OPTIM.TRAIN.COEFS.GENETIC.CLST = 0.
C.OPTIM.TRAIN.COEFS.GENETIC.SEP = 0.
C.OPTIM.TRAIN.COEFS.GENETIC.L1 = 0.
C.OPTIM.TRAIN.COEFS.GENETIC.ORTHO = 0.

C.OPTIM.TRAIN.COEFS.IMAGE = CfgNode()
C.OPTIM.TRAIN.COEFS.IMAGE.CRS_ENT = 0.
C.OPTIM.TRAIN.COEFS.IMAGE.CLST = 0.
C.OPTIM.TRAIN.COEFS.IMAGE.SEP = 0.
C.OPTIM.TRAIN.COEFS.IMAGE.L1 = 0.
C.OPTIM.TRAIN.COEFS.IMAGE.ORTHO = 0.


C.OPTIM.TRAIN.WARM = CfgNode()
C.OPTIM.TRAIN.WARM.ADD_ON_LAYERS_LR = 0.
C.OPTIM.TRAIN.WARM.ADD_ON_LAYERS_WD = 0.
C.OPTIM.TRAIN.WARM.PROTOTYPE_LR = 0.
C.OPTIM.TRAIN.WARM.PROTOTYPE_WD = 0.

# Joint optimizer
C.OPTIM.TRAIN.JOINT = CfgNode() 
C.OPTIM.TRAIN.JOINT.FEATURES_LR = 0.
C.OPTIM.TRAIN.JOINT.FEATURES_WD = 0.
C.OPTIM.TRAIN.JOINT.ADD_ON_LAYERS_LR = 0.
C.OPTIM.TRAIN.JOINT.ADD_ON_LAYERS_WD = 0.
C.OPTIM.TRAIN.JOINT.LAST_LAYER_LR = 0.
C.OPTIM.TRAIN.JOINT.LAST_LAYER_WD = 0.
C.OPTIM.TRAIN.JOINT.PROTOTYPE_LR = 0.
C.OPTIM.TRAIN.JOINT.PROTOTYPE_WD = 0.

# Last layer optimizer
C.OPTIM.TRAIN.LAST_LAYER= CfgNode()
C.OPTIM.TRAIN.LAST_LAYER.LAST_LAYER_LR = 0.
C.OPTIM.TRAIN.LAST_LAYER.LAST_LAYER_MOM = 0.

C.OPTIM.PUSH = CfgNode() 
C.OPTIM.PUSH.N_LAST_LAYER = 0
C.OPTIM.PUSH.EPOCHS = []

C.OPTIM.PRUNE = CfgNode() 
C.OPTIM.PRUNE.TYPE = ""
C.OPTIM.PRUNE.K = 0
C.OPTIM.PRUNE.TAU = 0
C.OPTIM.PRUNE.EPOCHS = []
C.OPTIM.PRUNE.GENETIC_MAX_NUM_PROTOTYPES_PER_CLASS = 0
C.OPTIM.PRUNE.IMAGE_MAX_NUM_PROTOTYPES_PER_CLASS = 0

# Output 
C.OUTPUT = CfgNode()
C.OUTPUT.SAVE_MODEL = False
C.OUTPUT.SAVE_MODEL_EPOCHS = []
C.OUTPUT.SAVE_IMAGES = False
C.OUTPUT.MODEL_DIR = ""
C.OUTPUT.IMAGE_DIR = ""

C.OUTPUT.WEIGHT_MATRIX_FILENAME = "" 
C.OUTPUT.PROTOTYPE_IMG_FILENAME_PREFIX = "" 
C.OUTPUT.PROTOTYPE_SELF_ACT_FILENAME_PREFIX = "" 
C.OUTPUT.PROTO_BOUND_BOXES_FILENAME_PREFIX = "" 

def get_cfg_defaults(): 
    return C.clone()
