RUN_NAME: "muchang_genetics"
# WANDB_MODE: "disabled" 

MODEL:
    GENETIC_BACKBONE_PATH: "backbones/genetic_species_001/genetic_species_001_best.pth"

DATASET:
    TREE_SPECIFICATION_FILE: "class_trees/all_species_120.json"

    TRAIN_NOT_CLASSIFIED_PROPORTIONS: [0, 0, 0, 0]
    MODE: 1
    TRAIN_VAL_TEST_SPLIT: [80, 20, 20] 

    TRAIN_BATCH_SIZE: 80
    TEST_BATCH_SIZE: 160
    TRAIN_PUSH_BATCH_SIZE: 20

    CACHED_DATASET_FOLDER: "pre_existing_datasets/small_dataset"
    
    DATA_FILE: "../datasets/source_files/metadata_cleaned_permissive.tsv" 
    IMAGE_PATH: "../datasets/full_bioscan_images/" 

    GENETIC:
        PROTOTYPE_SHAPE: (64, 1, 1)
        NUM_PROTOTYPES_PER_CLASS: 40
        MAX_NUM_PROTOTYPES_PER_CLASS: 8
OPTIM:
    NUM_WARM_EPOCHS: 3
    NUM_TRAIN_EPOCHS: 100
    PUSH_EPOCHS: []
    PRUNE_EPOCHS: []
    COEFS: 
        GENETIC: 
            CRS_ENT: 20.
            CLST: -1.0
            SEP: -1.0
            L1: 0.0
            ORTHO: 0.0
    WARM: 
        ADD_ON_LAYERS_LR: 3e-2 
        ADD_ON_LAYERS_WD: 0.
        PROTOTYPE_LR: 3e-2 
        PROTOTYPE_WD: 0.
    JOINT: 
        FEATURES_LR: 1e-2 
        FEATURES_WD: 0.
        ADD_ON_LAYERS_LR: 3e-2
        ADD_ON_LAYERS_WD: 1e-3
        LAST_LAYER_LR: 3e-2 
        LAST_LAYER_WD: 1e-3 
        PROTOTYPE_LR: 3e-2
        PROTOTYPE_WD: 0.
    LAST_LAYER: 
        LAST_LAYER_LR: 3e-2 
        LAST_LAYER_MOM: 0.9
        

OUTPUT:
    WEIGHT_MATRIX_FILENAME: "outputL_weights"
    PROTOTYPE_IMG_FILENAME_PREFIX: "prototype-img"
    PROTOTYPE_SELF_ACT_FILENAME_PREFIX: "prototype-self-act"
    PROTO_BOUND_BOXES_FILENAME_PREFIX: "bb"
