RUN_NAME: "genetics_120_8"
# WANDB_MODE: "online" 
MODE: 1

DATASET:
    HIERARCHY_FILE: "class_trees/all_species_120.json"

    CACHED_DATASET_FOLDER: "pre_existing_datasets/reasonable_dataset"
    
    DATA_FILE: "../datasets/source_files/metadata_cleaned_permissive.tsv" 
    IMAGE_PATH: "../datasets/full_bioscan_images/" 

MODEL:
    GENETIC:
        PROTOTYPE_SHAPE: (64, 1, 1)
