RUN_NAME: "muchang_genetics"
WANDB_MODE: "disabled" 

MODEL:
    GENETIC_BACKBONE_PATH: "backbones/genetic_species_001/genetic_species_001_best.pth"
    PRUNE: false
    PRUNING_TYPE: "weights"
    PRUNING_K: 8
    PRUNING_TAU: 8

DATASET:
    TREE_SPECIFICATION_FILE: "class_trees/all_species_120.json"

    TRAIN_NOT_CLASSIFIED_PROPORTIONS: [0, 0, 0, 0]
    MODE: 1
    TRAIN_VAL_TEST_SPLIT: [80, 20, 20] # Number of unaugmented samples per leaf in train, val, and test splits.

    TRAIN_BATCH_SIZE: 80

    # Uncomment these once datasets have already been generated and you want to reuse them
    # PRE_EXISTING_IMAGES: true
    CACHED_DATASET_FOLDER: "pre_existing_datasets/reasonable_dataset"
    
    DATA_FILE: "../datasets/source_files/metadata_cleaned_permissive.tsv" # Path to CSV from which data can be selected
    IMAGE_PATH: "../datasets/full_bioscan_images/" # Path to image directory

    GENETIC:
        PROTOTYPE_SHAPE: (64, 1, 1)
        NUM_PROTOTYPES_PER_CLASS: 40
        MAX_NUM_PROTOTYPES_PER_CLASS: 8
OPTIM:
    NUM_WARM_EPOCHS: 0
    NUM_TRAIN_EPOCHS: 20
    PUSH_EPOCHS: [0,10,15,20]
    PRUNE_START: 5
    COEFS:
        SEP: -0.1
    JOINT: False

OUTPUT:
    WEIGHT_MATRIX_FILENAME: "outputL_weights"
    PROTOTYPE_IMG_FILENAME_PREFIX: "prototype-img"
    PROTOTYPE_SELF_ACT_FILENAME_PREFIX: "prototype-self-act"
    PROTO_BOUND_BOXES_FILENAME_PREFIX: "bb"
