RUN_NAME: "image_120_reasonable"
WANDB_MODE: "online" 

DATASET:
    TREE_SPECIFICATION_FILE: "class_trees/all_species_120.json"
    TRAIN_NOT_CLASSIFIED_PROPORTIONS: [0, 0, 0, 0]
    MODE: 2
    TRAIN_VAL_TEST_SPLIT: [80, 20, 20] 

    CACHED_DATASET_FOLDER: "pre_existing_datasets/reasonable_dataset"
    
    DATA_FILE: "../datasets/source_files/metadata_cleaned_permissive.tsv" 
    IMAGE_PATH: "../datasets/full_bioscan_images/" 

    TRAIN_BATCH_SIZE: 80

    IMAGE:
        PROTOTYPE_SHAPE: (2048, 1, 1)
        TRANSFORM_MEAN: (0.706, 0.708, 0.709)
        TRANSFORM_STD: (0.146, 0.164, 0.1837)

        # old normalization parameters for CUB 
        # TRANSFORM_MEAN: (0.485, 0.456, 0.406)
        # TRANSFORM_STD: (0.229, 0.224, 0.225)
