RUN_NAME: "muchang_image"
# WANDB_MODE: "disabled" 

MODEL:
    PRUNE: false

DATASET:
    TREE_SPECIFICATION_FILE: "class_trees/all_species_120.json"
    TRAIN_NOT_CLASSIFIED_PROPORTIONS: [0, 0, 0, 0]
    MODE: 2
    TRAIN_VAL_TEST_SPLIT: [80, 20, 20] 

    CACHED_DATASET_FOLDER: "pre_existing_datasets/small_dataset"
    
    DATA_FILE: "../datasets/source_files/metadata_cleaned_permissive.tsv" # Path to CSV from which data can be selected
    IMAGE_PATH: "../datasets/full_bioscan_images/" # Path to image directory

    TRAIN_BATCH_SIZE: 40
    TEST_BATCH_SIZE: 40
    TRAIN_PUSH_BATCH_SIZE: 40

    IMAGE:
        PROTOTYPE_SHAPE: (2048, 1, 1)
        TRANSFORM_MEAN: (0.485, 0.456, 0.406)
        TRANSFORM_STD: (0.229, 0.224, 0.225)
        NUM_PROTOTYPES_PER_CLASS: 10
        # PPNET_PATH: "../output/image_only/150_Lite_ImageFullTest_003/15_push0.8515.pth"

OPTIM:
    NUM_WARM_EPOCHS: 3
    NUM_TRAIN_EPOCHS: 50
    PUSH_EPOCHS: []
    PUSH_EPOCHS: []
    COEFS: 
        IMAGE: 
            CRS_ENT: 20.
            CLST: 0.001
            SEP: -0.1
            L1: 5e-3
            ORTHOGONALITY: 1e-3

OUTPUT:
    WEIGHT_MATRIX_FILENAME: "outputL_weights"
    PROTOTYPE_IMG_FILENAME_PREFIX: "prototype-img"
    PROTOTYPE_SELF_ACT_FILENAME_PREFIX: "prototype-self-act"
    PROTO_BOUND_BOXES_FILENAME_PREFIX: "bb"
