RUN_NAME: "test_run"

DATASET:
    TREE_SPECIFICATION_FILE: "class_trees/example.json"
    TRAIN_NOT_CLASSIFIED_PROPORTIONS: [0, 0, .25, .5]
    MODE: 2 # This means the dataloader will return only images.
    TRAIN_VAL_TEST_SPLIT: [400, 40, 40] # Number of unaugmented samples per leaf in train, val, and test splits.
    OVERSAMPLING_RATE: 1 # How much augmenation we do. Must be 1 or a multiple of 4.

    DATA_FILE: "datasets/metadata/metadata_cleaned_permissive.tsv"

    # Uncomment these once datasets have already been generated and you want to reuse them
    # PRE_EXISTING_IMAGES: true
    # CACHED_DATASET_FOLDER: "pre_existing_datasets/test_run"

    IMAGE:
        PROTOTYPE_SHAPE: (400, 2048, 1, 1)
        TRAIN_BATCH_SIZE: 80
        TRANSFORM_MEAN: (0.485, 0.456, 0.406)
        TRANSFORM_STD: (0.229, 0.224, 0.225)

OPTIM:
    NUM_TRAIN_EPOCHS: 31
    # JOINT_OPTIMIZER_LAYERS:
    #     ADD_ON_LAYERS: 1e-3
    #     PROTOTYPE_VECTORS: 1e-3
    # WARM_OPTIMIZER_LAYERS:
    #     ADD_ON_LAYERS: 1e-3
    #     PROTOTYPE_VECTORS: 1e-3
    COEFS:
        SEP: -0.1
    JOINT: False

OUTPUT:
    WEIGHT_MATRIX_FILENAME: "outputL_weights"
    PROTOTYPE_IMG_FILENAME_PREFIX: "prototype-img"
    PROTOTYPE_SELF_ACT_FILENAME_PREFIX: "prototype-self-act"
    PROTO_BOUND_BOXES_FILENAME_PREFIX: "bb"
