RUN_NAME: "clst_neg_sep_pos"
SEED: 2024
MODE: 3
WANDB_MODE: "online" 
DEVICE: "cuda"

MODEL:
    IMAGE: 
        # PPNET_PATH: "../output/joint/genetic-prune-weight-5-protos_001/img_train_ep15.pth"
        BACKBONE_PATH: "backbones/image_120_reasonable_best.pth"
        PROTOTYPE_SHAPE: (64, 1, 1) 
        NUM_PROTOTYPES_PER_CLASS: 10
    GENETIC: 
        # PPNET_PATH: "../output/joint/genetic-prune-weight-5-protos_001/gen_train_ep15.pth"
        BACKBONE_PATH: "backbones/genetics_120_reasonable_best.pth"
        PROTOTYPE_SHAPE: (64, 1, 1)
        NUM_PROTOTYPES_PER_CLASS: 10
        FIXED_PROTOTYPES: False
        POSITION_ENCODING_TYPE: "two-late" # two: concatenate (cos(pos), sin(pos)) wth the latent embedding, two-late: same as above, but x = normalize(normalize(x)::(cos(pos), sin(pos)))

DATASET:
    IMAGE_PATH: "../datasets/full_bioscan_images/" 
    DATA_FILE:  "../datasets/source_files/metadata_cleaned_permissive.tsv" 
    HIERARCHY_FILE: "class_trees/all_species_120.json" 

    CACHED_DATASET_FOLDER: "pre_existing_datasets/small_dataset"
    # CACHED_DATASET_FOLDER: "pre_existing_datasets/reasonable_dataset"

    TRAIN_NOT_CLASSIFIED_PROPORTIONS: [0, 0, 0, 0] 
    TRAIN_VAL_TEST_SPLIT: [80, 20, 20] 

    TRANSFORMS: 
        IMAGE: 
            SIZE: 256
            MEAN: (0.706, 0.708, 0.709)
            STD: (0.146, 0.164, 0.1837)
        GENETIC:
            SUBSTITUTION_RATE: 0.05  
            DELETION_COUNT: 4 
            INSERTION_COUNT: 4

    TRAIN_BATCH_SIZE: 60
    TEST_BATCH_SIZE: 60
    PUSH_BATCH_SIZE: 60

OPTIM:
    NUM_WARM_EPOCHS: 10
    NUM_EPOCHS: 200
    TRAIN: 
        CORRESPONDENCE_TYPE: "Batched"
        COEFS: 
            CORRESPONDENCE: 0.0
            GENETIC: 
                CRS_ENT: 20.
                CLST: -.01
                SEP: .001
                L1: 0.0
                ORTHO: 0.0
            IMAGE: 
                # should be ~10 times the values of genetic from experiments
                CRS_ENT: 20.
                CLST: -1.0
                SEP: 1.0
                L1: 0.0
                ORTHO: 0.0
        WARM: 
            ADD_ON_LAYERS_LR: 3e-2 
            ADD_ON_LAYERS_WD: 0.
            PROTOTYPE_LR: 3e-2 
            PROTOTYPE_WD: 0.
        JOINT: 
            FEATURES_LR: 1e-2 
            FEATURES_WD: 0.
            ADD_ON_LAYERS_LR: 1e-2
            ADD_ON_LAYERS_WD: 1e-3
            # LAST_LAYER_LR: 1e-2 
            LAST_LAYER_LR: 0.0
            LAST_LAYER_WD: 1e-3 
            PROTOTYPE_LR: 1e-2
            PROTOTYPE_WD: 0.
        LAST_LAYER: 
            LAST_LAYER_LR: 1e-2 
            LAST_LAYER_MOM: 0.9
    PUSH: 
        # EPOCHS: [15, 40, 80, 120]
        EPOCHS: [30, 60, 90]
        N_LAST_LAYER: 19
    PRUNE: 
        TYPE: "weights" 
        K: 6 
        TAU: 5
        EPOCHS: []
        GENETIC_MAX_NUM_PROTOTYPES_PER_CLASS: 5
        IMAGE_MAX_NUM_PROTOTYPES_PER_CLASS: 10

OUTPUT:
    SAVE_MODEL: True 
    SAVE_MODEL_EPOCHS: [39, 79]
    SAVE_IMAGES: True
    MODEL_DIR: ""
    IMAGE_DIR: ""

    WEIGHT_MATRIX_FILENAME: "outputL_weights"
    PROTOTYPE_IMG_FILENAME_PREFIX: "prototype-img"
    PROTOTYPE_SELF_ACT_FILENAME_PREFIX: "prototype-self-act"
    PROTO_BOUND_BOXES_FILENAME_PREFIX: "bb"
