RUN_NAME: "push_save_test"
WANDB_MODE: "disabled" 

MODEL:
    PRUNE: false # Keep disabled. This has not been updated to work with new changes.
    GENETIC_BACKBONE_PATH: "backbones/genetic_species_001/genetic_species_001_best.pth"

    # BUGFIX!
    # MULTI: # There are some issues with preloading old multi_ppnets because the model code has changed. Look into this.
    #     MULTI_PPNET_PATH: "../output/joint/parallel_new_backbone_10epoch_init_067/10push0.3333.pth"

DATASET:
    TREE_SPECIFICATION_FILE: "class_trees/all_species_120.json" # Always use class_trees/all_species_120.json
    TRAIN_NOT_CLASSIFIED_PROPORTIONS: [0, 0, 0, 0] # Always set to [0,0,0,0]
    TRAIN_VAL_TEST_SPLIT: [80, 20, 20] # Number of unaugmented samples per leaf in train, val, and test splits. If you're making a new dataset (i.e. you don't have CACHED_DATASET_FOLDER definted.) This will be used. It mustn't sum to more than 120.
    CACHED_DATASET_FOLDER: "pre_existing_datasets/small_dataset"
    
    MODE: 3 # For parallel mode, always set to 3

    IMAGE_PATH: "../datasets/full_bioscan_images/" # Path to image directory. Never change.
    TRAIN_BATCH_SIZE: 40
    TEST_BATCH_SIZE: 160
    TRAIN_PUSH_BATCH_SIZE: 40

    IMAGE: 
        PROTOTYPE_SHAPE: (2048, 1, 1) 
        TRANSFORM_MEAN: (0.485, 0.456, 0.406)
        TRANSFORM_STD: (0.229, 0.224, 0.225)
        NUM_PROTOTYPES_PER_CLASS: 10
        # PPNET_PATH: "../output/image_only/image_species_120_80train_warm_001/images/10_push_weights.pth" # Path to pretrained image ppnet. This can be used in multimodal mode.
    GENETIC:
        PROTOTYPE_SHAPE: (64, 1, 1)
        NUM_PROTOTYPES_PER_CLASS: 40
        # PPNET_PATH: "../output/genetic_only/genetic_species_warm_001/images/10_push_weights.pth" # Path to pretrained genetic ppnet. This can be used in multimodal mode.
OPTIM:
    NUM_WARM_EPOCHS: 3
    NUM_TRAIN_EPOCHS: 100
    PUSH_EPOCHS: [0]
    COEFS: 
        CORRESPONDENCE: 1000.0
        GENETIC: 
            CRS_ENT: 20.
            CLST: 0.001
            SEP: -0.1
            L1: 5e-3
            ORTHOGONALITY: 1e-3
        IMAGE: 
            CRS_ENT: 20.
            CLST: 0.001
            SEP: -0.1
            ORTHOGONALITY: 1e-3

    # Optimizer Learning Rates (LR) and Weight Decays (WD) 
    WARM: 
        ADD_ON_LAYERS_LR: 3e-3 
        ADD_ON_LAYERS_WD: 1e-3
        PROTOTYPE_LR: 3e-3 
        PROTOTYPE_WD: 1e-3 
    JOINT: 
        FEATURES_LR: 1e-5 
        FEATURES_WD: 1e-3
        ADD_ON_LAYERS_LR: 3e-3
        ADD_ON_LAYERS_WD: 1e-3
        LAST_LAYER_LR: 3e-3 
        LAST_LAYER_WD: 1e-3 
        PROTOTYPE_LR: 3e-4
        PROTOTYPE_WD: 1e-3
    LAST_LAYER: 
        LAST_LAYER_LR: 3e-3 
        LAST_LAYER_MOM: 0.9
        

OUTPUT:
    WEIGHT_MATRIX_FILENAME: "outputL_weights"
    PROTOTYPE_IMG_FILENAME_PREFIX: "prototype-img"
    PROTOTYPE_SELF_ACT_FILENAME_PREFIX: "prototype-self-act"
    PROTO_BOUND_BOXES_FILENAME_PREFIX: "bb"
    SAVE: False # If this is false, images won't be saved.